apiVersion: v1
kind: Service
metadata:
  name: skyfactory
  labels:
    app: skyfactory
spec:
  ports:
  - port: 25565
    name: minecraft
  selector:
    app: skyfactory
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: skyfactory
spec:
  selector:
    matchLabels:
      app: skyfactory
  serviceName: "skyfactory"
  replicas: 1
  template:
    metadata:
      labels:
        app: skyfactory
    spec:
      containers:
      - name: skyfactory
        image: ghcr.io/natsutarous/skyfactory4:4.2.4.latest
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
        - name: world
          mountPath: /skyfactory/world
      volumes:
      - name: world
        emptyDir: {}
